name: Deploy dave-kav.com (Preview)

on:
  pull_request:
    paths:
      - 'apps/com/**'
      - 'packages/config/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy-app-preview.yml
    with:
      app: com
    secrets: inherit
