name: Deploy dave-kav.dev

on:
  push:
    branches: [main]
    paths:
      - 'apps/dev/**'
      - 'packages/config/**'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-app.yml
    with:
      app: dev
    secrets: inherit
